### ISSUE TITLE
windows 10 docker start fail

### ISSUE THREAD

**Issue by Newoptionz** [PacktPublishing/Jupyter-Notebook-for-Data-Science#1]
Windows 10, 64
so when I try run 
'docker run -it -p 8888:8888 -v C:\Users\Stephen\Documents\Python_JupyterforDS\jupyter-course jupyter/datascience-notebook'

I keep getting errors like

docker: Error response from daemon: driver failed programming external connectivity on endpoint pensive_driscoll (39bbe3ddb21fe6e8d5487837f463def8d406d3017b06809e9becd1637e7b7f79): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8888:tcp:172.17.0.2:8888: input/output error.

seems related to 'https://github.com/docker/for-win/issues/573' 

Any help?

**Comment by Newoptionz** [comment]
So after doing a docker restart 'docker settings' I get the following error
'docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.'

**Comment by thomas-schuster** [comment]
Hey there, for this type of error, Docker offers the following resolution: 
Restart Docker Windows Service
(see [Docker Support](https://success.docker.com/article/docker-for-windows-fails-with-a-daemon-not-running-message))

If that does not resolve your issue: 

- which Version of Windows 10 do you use?
- did you check your settings (as described in requirements for [installing Docker on Windows](https://docs.docker.com/docker-for-windows/install/)
